name: Update JioTV Cookies

on:
  schedule:
    # Run every 6 hours (CRON format: minute hour day month day-of-week)
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-cookies:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permission to write to repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Token for pushing changes

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        pip install requests

    - name: Extract __hdnea__ cookie and update jiotv.json
      run: |
        python3 -c "
        import requests
        import json
        import sys

        # Hard-coded Main URL
        url = 'https://jo-json.vodep39240327.workers.dev/'

        # Try GET request to get cookies
        try:
            response = requests.get(url, timeout=10)
            response.raise_for_status()  # Raise error for bad status codes
        except requests.RequestException as e:
            print(f'Error fetching URL: {e}')
            sys.exit(1)

        # Extract __hdnea__ cookie
        hdnea_cookie = None
        for cookie in response.cookies:
            if cookie.name == '__hdnea__':
                hdnea_cookie = f'__hdnea__={cookie.value}'
                break

        # Load existing jiotv.json if it exists
        try:
            with open('jiotv.json', 'r') as f:
                data = json.load(f)
        except FileNotFoundError:
            data = []  # Initialize empty list if file doesn't exist
        except json.JSONDecodeError as e:
            print(f'Error decoding jiotv.json: {e}')
            sys.exit(1ස

        # Update cookie field for all channels
        if hdnea_cookie and data:  # Check if cookie and data exist
            for channel in data:
                channel['cookie'] = hdnea_cookie
            print(f'Updated cookies with: {hdnea_cookie}')
        else:
            print('Warning: __hdnea__ cookie not found or jiotv.json is empty')

        # Write to jiotv.json
        try:
            with open('jiotv.json', 'w') as f:
                json.dump(data, f, indent=4)
            print('jiotv.json updated successfully')
        except Exception as e:
            print(f'Error writing to jiotv.json: {e}')
            sys.exit(1)

        print('jiotv.json content:')
        print(json.dumps(data, indent=2))
        "

    - name: Commit and push updated jiotv.json
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add jiotv.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m 'Update __hdnea__ cookie in jiotv.json [skip ci]'
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
