name: Auto Update JioTV Cookies
on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours (12:00 AM, 6:00 AM, 12:00 PM, 6:00 PM IST)
  workflow_dispatch: # Manual trigger
jobs:
  update-cookies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Fetch JSON and Update Jiotv.json
        run: |
          echo "Fetching JSON from https://jo-json.vodep39240327.workers.dev/"
          curl -s -f https://jo-json.vodep39240327.workers.dev/ > stream.json || {
            echo "ERROR: Failed to fetch JSON. Check URL or network."
            exit 1
          }
          if [ ! -s stream.json ]; then
            echo "ERROR: JSON file is empty."
            exit 1
          fi
          echo "Checking for url field..."
          if ! jq -e '.url' stream.json >/dev/null 2>&1; then
            echo "ERROR: url field not found in JSON."
            cat stream.json
            exit 1
          fi
          URL=$(jq -r '.url' stream.json)
          echo "Extracted URL: $URL"
          NEW_COOKIE=$(echo "$URL" | grep -oE '__hdnea__=[^& ]+' | cut -d'=' -f2- || echo "null")
          if [ "$NEW_COOKIE" = "null" ]; then
            echo "ERROR: No __hdnea__ cookie found in URL."
            echo "URL: $URL"
            exit 1
          fi
          echo "Cookie extracted: $NEW_COOKIE"
          # Initialize Jiotv.json if missing or invalid
          if [ ! -f Jiotv.json ] || ! jq -e . Jiotv.json >/dev/null 2>&1; then
            echo '[{"cookie": ""}]' > Jiotv.json
            echo "Initialized Jiotv.json with default structure."
          fi
          # Update cookie in Jiotv.json
          jq --arg new_cookie "$NEW_COOKIE" 'map(.cookie = $new_cookie)' Jiotv.json > Jiotv_temp.json || {
            echo "ERROR: Failed to update Jiotv.json."
            cat Jiotv.json
            exit 1
          }
          mv Jiotv_temp.json Jiotv.json
          echo "Updated Jiotv.json with new cookie: $NEW_COOKIE"
          echo "Preview of Jiotv.json (first entry's cookie):"
          jq '.[0].cookie' Jiotv.json || echo "No valid JSON to preview"
      - name: Commit and Push Changes
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add Jiotv.json
          # Force commit to ensure update every run
          git commit -m "Update JioTV cookie ($(date -u '+%Y-%m-%d %H:%M:%S UTC') - ${{ github.sha }})" --no-verify --allow-empty
          git push || {
            echo "ERROR: Git push failed. Check GITHUB_TOKEN or permissions."
            git status
            exit 1
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
