# .github/workflows/update-jiotv-cookies.yml

name: Update JioTV Cookies in Jiotv.json

on:
  schedule:
    - cron: '0 */6 * * *'   # Har 6 ghante mein (UTC)
  workflow_dispatch:        # Manual run allowed

jobs:
  update-cookies:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Git push ke liye

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requests
        run: pip install requests

      - name: Create/Update Jiotv.json with Fresh Cookies
        run: |
          python - <<'PY'
          import json
          import requests
          import os

          URL = "https://jo-json.vodep39240327.workers.dev"
          PLAYLIST = "Jiotv.json"

          def get_cookie():
              try:
                  resp = requests.get(URL, timeout=10)
                  resp.raise_for_status()
                  cookies = resp.cookies.get_dict()
                  return "; ".join(f"{k}={v}" for k, v in cookies.items())
              except Exception as e:
                  print(f"Cookie fetch failed: {e}")
                  exit(1)

          def load_playlist():
              if not os.path.exists(PLAYLIST):
                  print(f"{PLAYLIST} not found! Creating default...")
                  return [
                      {
                          "logo": "https://img.media.jio.com/tvpimages/66/40/302084_1753189751700_l_high.jpg",
                          "name": "Star Plus",
                          "link": "http://jiotvbpkmob.cdn.jio.com/bpk-tv/Star_Plus_BTS/output/index.mpd",
                          "drmScheme": "clearkey",
                          "drmLicense": "3bba2ffaf08b501796c5d9eb431460a4:7a62074c4c46f3b153259526481c02bf",
                          "cookie": ""
                      }
                  ]
              with open(PLAYLIST, 'r', encoding='utf-8') as f:
                  return json.load(f)

          def save_playlist(data):
              with open(PLAYLIST, 'w', encoding='utf-8') as f:
                  json.dump(data, f, indent=2, ensure_ascii=False)

          # Main
          new_cookie = get_cookie()
          print(f"New Cookie: {new_cookie[:100]}...")

          playlist = load_playlist()
          if not isinstance(playlist, list):
              print("Invalid playlist format!")
              exit(1)

          updated = False
          for ch in playlist:
              if "cookie" in ch and ch["cookie"] != new_cookie:
                  ch["cookie"] = new_cookie
                  print(f"Updated: {ch.get('name', 'Unknown')}")
                  updated = True

          if updated or not os.path.exists(PLAYLIST):
              save_playlist(playlist)
              print("Jiotv.json updated.")
          else:
              print("No changes needed.")
          PY

      - name: Commit & Push Jiotv.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Jiotv.json
          git commit -m "Auto: Updated cookies in Jiotv.json" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
