name: Auto Update ZEE5 Cookie (Dedicated Workflow Every 4 Hours)
on:
  schedule:
    - cron: '30 */4 * * *' # Har 4 ghante (5:30, 9:30, 1:30, 5:30, 9:30 IST)
  workflow_dispatch: # Manual trigger
jobs:
  update-zee5-cookie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Fetch and Debug new URL
        run: |
          echo "=== Fetching from https://doctor-strange.developed-for-wanda.workers.dev/ ==="
          curl -s https://doctor-strange.developed-for-wanda.workers.dev/ > stream.json
          if [ ! -s stream.json ]; then
            echo "✗ ERROR: Failed to fetch stream.json. File is empty."
            exit 1
          fi
          echo "File size: $(wc -c < stream.json) bytes"
          echo "Full stream.json preview (first 1000 chars):"
          head -c 1000 stream.json | tr -d '\n' | sed 's/"/\\"/g' | fold -w 80
          echo "Searching for JITENDRAUNATTI.ZEE5.Cookie..."
          if jq -e '.JITENDRAUNATTI.ZEE5.Cookie' stream.json >/dev/null 2>&1; then
            echo "✓ ZEE5 cookie found in file!"
          else
            echo "✗ ZEE5 cookie NOT found. Dumping first 200 lines:"
            head -n 200 stream.json
            exit 1
          fi
      - name: Extract Cookies and Update Zee5.json
        run: |
          echo "=== Extracting ZEE5 Cookie ==="
          NEW_ZEE5_COOKIE=$(jq -r '.JITENDRAUNATTI.ZEE5.Cookie' stream.json 2>/dev/null || echo "null")
          if [ "$NEW_ZEE5_COOKIE" = "null" ]; then
            echo "✗ ERROR: No valid ZEE5 cookie found. Using previous value."
            NEW_ZEE5_COOKIE=$(jq -r '.[0].cookie' Zee5.json 2>/dev/null || echo "")
          fi
          echo "✓ Full ZEE5 cookie extracted: $NEW_ZEE5_COOKIE"

          echo "=== Updating Zee5.json ==="
          cp Zee5.json Zee5_backup.json 2>/dev/null || echo "Zee5.json not found, creating new."
          if [ ! -s Zee5_backup.json ]; then
            echo "✗ ERROR: Zee5.json is empty or missing. Creating a basic structure."
            echo '[]' > Zee5_backup.json
          fi
          if ! jq -e . Zee5_backup.json >/dev/null 2>&1; then
            echo "✗ WARNING: Zee5.json is invalid JSON. Attempting recovery..."
            tail -n +10 Zee5_backup.json > temp_backup.json 2>/dev/null || echo '[]' > temp_backup.json
            mv temp_backup.json Zee5_backup.json
            if ! jq -e . Zee5_backup.json >/dev/null 2>&1; then
              echo "✗ ERROR: Recovery failed. Creating a fallback JSON with ZEE5 cookie."
              echo '[{"cookie": "'"$NEW_ZEE5_COOKIE"'"}]' > Zee5_backup.json
            fi
          fi
          # Update only the cookie field in Zee5.json
          jq --arg zee5cookie "$NEW_ZEE5_COOKIE" 'map(if .cookie then .cookie = $zee5cookie else . + {"cookie": $zee5cookie} end)' Zee5_backup.json > Zee5_updated.json
          mv Zee5_updated.json Zee5.json
          git add Zee5.json

          echo "✓ Zee5.json update complete. New cookie: $NEW_ZEE5_COOKIE"
          echo "Preview of updated Zee5.json (first entry's cookie):"
          jq '.[0].cookie' Zee5.json 2>/dev/null || echo "No valid JSON to preview"
          echo "Full updated Zee5.json preview (first 200 chars):"
          head -c 200 Zee5.json

          if ! diff -q Zee5_backup.json Zee5.json 2>/dev/null; then
            echo "✓ Zee5.json file changed!"
          else
            echo "✗ No change detected in Zee5.json, but forcing commit."
          fi
      - name: Force Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Zee5.json
          # Always force commit with a hidden file to ensure push
          touch .force-update-timestamp
          git add .force-update-timestamp
          git commit -m "Force auto-update ZEE5 cookie in Zee5.json (new: ${{ github.sha }}) --no-verify" || {
            echo "✗ ERROR: Commit failed. Creating fallback commit."
            echo '{"update": "forced"}' > .force-commit.json
            git add .force-commit.json
            git commit -m "Fallback force update ZEE5 cookie (new: ${{ github.sha }}) --no-verify" || {
              echo "✗ FATAL: Fallback commit also failed. Dumping git status:"
              git status
              exit 1
            }
          }
          git push || {
            echo "✗ ERROR: Git push failed. Checking GITHUB_TOKEN or repo permissions."
            echo "Dumping git status:"
            git status
            exit 1
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
