name: Update JioTV Cookies

on:
  schedule:
    # Har 6 ghante mein chalao (CRON format: minute hour day month day-of-week)
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Manual trigger ke liye

jobs:
  update-cookies:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # File update ke liye

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Push ke liye

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Extract __hdnea__ cookie and update jiotv.json
      run: |
        # Inline Python script to extract __hdnea__ cookie
        python3 -c "
import requests
import json

# Hard-coded Main URL
url = 'https://jo-json.vodep39240327.workers.dev/'

# Default JSON structure for jiotv.json
default_data = {
    'logo': 'https://img.media.jio.com/tvpimages/66/40/302084_1753189751700_l_high.jpg',
    'name': 'Star Plus',
    'link': 'http://jiotvbpkmob.cdn.jio.com/bpk-tv/Star_Plus_BTS/output/index.mpd',
    'drmScheme': 'clearkey',
    'drmLicense': '3bba2ffaf08b501796c5d9eb431460a4:7a62074c4c46f3b153259526481c02bf',
    'cookie': ''
}

# HEAD request to get cookies
response = requests.head(url)
hdnea_cookie = None

# Extract __hdnea__ cookie
for cookie in response.cookies:
    if cookie.name == '__hdnea__':
        hdnea_cookie = f'__hdnea__={cookie.value}'
        break

# Load existing jiotv.json if it exists
try:
    with open('jiotv.json', 'r') as f:
        data = json.load(f)
except FileNotFoundError:
    data = default_data

# Update cookie field if __hdnea__ was found
if hdnea_cookie:
    data['cookie'] = hdnea_cookie
else:
    print('Warning: __hdnea__ cookie not found')

# Write to jiotv.json
with open('jiotv.json', 'w') as f:
    json.dump(data, f, indent=4)

print('jiotv.json updated with cookie:')
print(json.dumps(data, indent=2))
        "

    - name: Commit and push updated jiotv.json
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add jiotv.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m 'Update __hdnea__ cookie in jiotv.json [skip ci]'
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
