name: Update JioTV Cookies

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-cookies:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Fetch cookies and update Ziotv.json
      - name: Fetch cookies and update JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python - <<EOF
          import requests
          import json
          import re
          import os

          # URL to fetch cookies
          m3u_url = "https://raw.githubusercontent.com/alex8875/m3u/refs/heads/main/jtv.m3u"

          # Fetch the m3u file
          response = requests.get(m3u_url)
          response.raise_for_status()
          m3u_content = response.text

          # Extract cookies using regex
          cookie_pattern = r'__hdnea__=[^;]+'
          cookie_match = re.search(cookie_pattern, m3u_content)
          if not cookie_match:
            print("No cookie found in the m3u file")
            exit(1)
          new_cookie = cookie_match.group(0)

          # Path to Ziotv.json
          json_file = "Ziotv.json"

          # Read existing Ziotv.json
          if os.path.exists(json_file):
            with open(json_file, 'r') as f:
              data = json.load(f)
          else:
            print(f"{json_file} not found")
            exit(1)

          # Update cookie in the JSON data
          updated = False
          if isinstance(data, list):
            for item in data:
              if "cookie" in item:
                item["cookie"] = new_cookie
                updated = True
          elif isinstance(data, dict) and "cookie" in data:
            data["cookie"] = new_cookie
            updated = True

          if not updated:
            print("No cookie field found to update in JSON")
            exit(1)

          # Write updated JSON back to file
          with open(json_file, 'w') as f:
            json.dump(data, f, indent=2)

          print("Cookies updated successfully")
          EOF

      # Commit and push changes
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add Ziotv.json
          git commit -m "Update cookies in Ziotv.json" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
