name: Update JioTV Cookies

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours (0:00, 6:00, 12:00, 18:00 UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  update-cookies:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history to ensure git can detect changes

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install requests library
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Fetch cookies and update Ziotv.json
      - name: Update cookies in Ziotv.json
        run: |
          python - <<EOF
          import requests
          import json
          import re
          import os

          # URL to fetch cookies
          m3u_url = "https://raw.githubusercontent.com/alex8875/m3u/refs/heads/main/jtv.m3u"

          # Fetch the m3u file
          try:
            response = requests.get(m3u_url, timeout=10)
            response.raise_for_status()
            m3u_content = response.text
          except requests.RequestException as e:
            print(f"Error fetching m3u file: {e}")
            exit(1)

          # Debug: Print m3u content (first 2000 chars) to check cookie presence
          print(f"m3u content (first 2000 chars):\n{m3u_content[:2000]}")

          # Extract the first __hdnea__ cookie
          cookie_pattern = r'__hdnea__=[^\s"\n;)(]+'
          cookie_match = re.search(cookie_pattern, m3u_content)
          if not cookie_match:
            print("Error: No __hdnea__ cookie found in the m3u file")
            exit(1)
          new_cookie = cookie_match.group(0).strip()

          # Debug: Print extracted cookie
          print(f"Extracted cookie: {new_cookie}")

          # Path to Ziotv.json
          json_file = "Ziotv.json"

          # Check if Ziotv.json exists
          if not os.path.exists(json_file):
            print(f"Error: {json_file} not found in repository root")
            exit(1)

          # Read Ziotv.json
          try:
            with open(json_file, 'r') as f:
              data = json.load(f)
          except json.JSONDecodeError as e:
            print(f"Error: Invalid JSON in {json_file}: {e}")
            exit(1)

          # Debug: Print JSON structure
          print(f"JSON data:\n{json.dumps(data, indent=2)[:2000]}")

          # Update cookie field for all channels
          updated = False
          if isinstance(data, list):
            for index, item in enumerate(data):
              if not isinstance(item, dict):
                print(f"Error: Item at index {index} is not a dictionary")
                continue
              if "cookie" not in item:
                print(f"Error: No cookie field in item at index {index} (name: {item.get('name', 'unknown')})")
                continue
              old_cookie = item["cookie"]
              item["cookie"] = new_cookie
              updated = True
              print(f"Updated cookie for {item.get('name', 'unknown')} (index {index}): {old_cookie} -> {new_cookie}")
          elif isinstance(data, dict):
            if "cookie" not in data:
              print("Error: No cookie field in Ziotv.json dictionary")
              exit(1)
            old_cookie = data["cookie"]
            data["cookie"] = new_cookie
            updated = True
            print(f"Updated cookie: {old_cookie} -> {new_cookie}")
          else:
            print("Error: Ziotv.json is neither a list nor a dictionary")
            exit(1)

          if not updated:
            print("Error: No cookie fields were updated in Ziotv.json")
            exit(1)

          # Write updated JSON back
          try:
            with open(json_file, 'w') as f:
              json.dump(data, f, indent=2)
              f.write('\n') # Ensure file ends with newline
            print(f"Successfully wrote updated {json_file}")
          except Exception as e:
            print(f"Error writing to {json_file}: {e}")
            exit(1)
          EOF

      # Commit and push changes with github-actions bot
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Ziotv.json
          git commit -m "Update cookies in Ziotv.json (Run: $(date -u '+%Y-%m-%d %H:%M:%S UTC'))" --allow-empty
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
