name: Update Cookies in Ziotv.json

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours (UTC, 5:30 AM, 9:30 AM, 1:30 PM, 5:30 PM IST)
  workflow_dispatch: # Allows manual triggering

jobs:
  update-cookies:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Create and run update script
      - name: Create and run update script
        run: |
          cat << 'EOF' > update_cookies.py
          import json
          import requests
          import os

          # Environment variables
          MAIN_URL = os.getenv('MAIN_URL')
          PLAYLIST_FILE = os.getenv('PLAYLIST_FILE')

          def fetch_cookie(url):
              """Fetch cookie from the main URL (JSON format)."""
              try:
                  response = requests.get(url)
                  response.raise_for_status()
                  print(f"Successfully fetched data from {url}")
                  data = response.json()
                  cookie = data.get('cookie')
                  if cookie:
                      print(f"Found cookie: {cookie}")
                      return cookie
                  else:
                      print("No 'cookie' key found in JSON response")
                      return None
              except requests.RequestException as e:
                  print(f"Error fetching JSON from {url}: {e}")
                  return None
              except ValueError as e:
                  print(f"Error parsing JSON response: {e}")
                  return None

          def update_json_playlist(playlist_file, cookie):
              """Update cookie in all entries of the JSON playlist."""
              try:
                  with open(playlist_file, 'r') as f:
                      playlist = json.load(f)
                  print(f"Loaded {playlist_file} with {len(playlist)} channels")
                  
                  # Assuming playlist is a list of channel objects
                  updated = False
                  for channel in playlist:
                      old_cookie = channel.get('cookie', 'None')
                      channel['cookie'] = cookie
                      updated = True
                      print(f"Updated cookie for {channel.get('name')}: {old_cookie} -> {cookie}")
                  
                  if updated:
                      # Write updated JSON back to file
                      with open(playlist_file, 'w') as f:
                          json.dump(playlist, f, indent=2)
                      print(f"Updated cookies in {playlist_file}")
                  else:
                      print("No channels found to update cookies")
              except Exception as e:
                  print(f"Error updating JSON playlist: {e}")

          def main():
              # Fetch cookie from JSON
              cookie = fetch_cookie(MAIN_URL)
              if not cookie:
                  print("No cookie to update, exiting")
                  return
              
              # Update JSON playlist
              update_json_playlist(PLAYLIST_FILE, cookie)

          if __name__ == '__main__':
              main()
          EOF

          python update_cookies.py
        env:
          MAIN_URL: https://raw.githubusercontent.com/alex8875/m3u/refs/heads/main/jtv.m3u
          PLAYLIST_FILE: Ziotv.json

      # Step 5: Commit and push changes
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Ziotv.json
          git commit -m 'Auto-update cookies in Ziotv.json' || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
